const Investor = require("../model/Investor");
const fetch = require('node-fetch')

const verifyToken = async (req, res, next) => {
  console.log(req.cookies.session, 'COOKIE VERIFICATION');
  try {
    const user = await ('https://www.googleapis.com/oauth2/v3/tokeninfo?id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjZhMWQyNmQ5OTJiZTdhNGI2ODliZGNlMTkxMWY0ZTlhZGM3NWQ5ZjEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXpwIjoiNzgwNTgyNDY0MTYxLTA2aGR0b242amU2bzB1dTQ4NWYwcnRiZGVqN3JudmY1LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiYXVkIjoiNzgwNTgyNDY0MTYxLTA2aGR0b242amU2bzB1dTQ4NWYwcnRiZGVqN3JudmY1LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTE1NjU2NDI5NjIwMjcwMTM2OTI5IiwiZW1haWwiOiJzbHMxODgxQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhdF9oYXNoIjoiU3kyQUgtU09VOEJPM3Z1WHNwWU5tUSIsIm5hbWUiOiJTaGVsYnkgU3Ryb3VzZSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQVRYQUp6aWszVHlFelhUaThiQ2JVYnF5eXdvUk5mNFF3U2xEWTlPTXpMYT1zOTYtYyIsImdpdmVuX25hbWUiOiJTaGVsYnkiLCJmYW1pbHlfbmFtZSI6IlN0cm91c2UiLCJsb2NhbGUiOiJlbiIsImlhdCI6MTYyMzQ1MDcxNCwiZXhwIjoxNjIzNDU0MzE0LCJqdGkiOiI2NDAzNWY4ZTVlNmFkOWMwOTg3MzdiM2NiNTMyY2RlODdjMTcwMGU5In0.rQfkz-zlaSByfwiCsQO-mLswcZuUP4wilat29BiTXOEqrgBB6-DzLXK2BWBKBIg_puVmEa0AxoI_hZKBxgy3pRbioXJjuW-cnXEK6WSLvFG2T9XXvIE_f_docREKzDYTct8jvZ6qaiBj3yeL5CYidP0pzayq9jrLnbHHqTTKfJXXmD2UKlACTMdpq4Cl-uG7Z4bWAXrc_ZJkv1vv2R-0lutw8QZtg2LxGCOFEtDr7qW8kFXp-5rTuN9Nnb2GmbuZ32xRAj2AASpnkkRu4IfrmHfH6YX7fAE-ZfWx_iSQlrBwZPP4A6vzs_ST7RPGPgQGyCg3qFO-pIJVjPTptvMCgQ');
    req.user = user;
    next();
  } catch (err) {
    err.status = 401;
    next(err);
  }
};

module.exports = verifyToken;
